ecommerce_pipeline:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: "{{ env_var('BQ_PROJECT_ID') }}"
      dataset: ecommerce_staging
      location: US
      threads: 2
      timeout_seconds: 300

    prod:
      type: bigquery
      method: service-account
      project: "{{ env_var('BQ_PROJECT_ID') }}"
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      dataset: ecommerce_staging
      location: US
      threads: 4
      timeout_seconds: 300
